sudo: required
services:
  - docker

before_install:
  - docker build -t marius24/frontend-notepad-test -f ./frontend/Dockerfile.test ./frontend

script:
  - docker run marius24/frontend-notepad-test npm test -- --coverage

after_success:
  - docker build -t marius24/frontendnotepad ./frontend
  - docker build -t marius24/nginxnotepad ./nginx
  - docker build -t marius24/backendnotepad .

  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin

  - docker push marius24/frontendnotepad
  - docker push  marius24/nginxnotepad
  - docker push marius24/backendnotepad
# READY FOR DEPLOMENT CONFIGURATION TO AWS
